"""Writes lib/pdfjsBundle.ts: the pdf.js library and its worker as strings.

The phone reads a statement PDF inside a hidden WebView, which has no network
and no file access, so the library ships inside the app instead. Run this again
when pdfjs-dist is upgraded in artifacts/family-budget:

    python scripts/gen_pdfjs_bundle.py
"""
import json
import os

here = os.path.dirname(os.path.abspath(__file__))
build = os.path.join(here, '..', '..', 'family-budget', 'node_modules', 'pdfjs-dist')
version = json.load(open(os.path.join(build, 'package.json'), encoding='utf8'))['version']


def read(name):
    return open(os.path.join(build, 'legacy', 'build', name), encoding='utf8').read()


def literal(text):
    # `</` is escaped so the text can sit inside an inline script without ending it.
    return json.dumps(text, ensure_ascii=True).replace('</', r'<\/')


out = os.path.join(here, '..', 'lib', 'pdfjsBundle.ts')
with open(out, 'w', encoding='utf8', newline='\n') as f:
    f.write('// Generated by scripts/gen_pdfjs_bundle.py from pdfjs-dist. Do not edit.\n')
    f.write(f"export const PDFJS_VERSION = '{version}';\n")
    f.write(f"export const PDFJS_MAIN = {literal(read('pdf.min.mjs'))};\n")
    f.write(f"export const PDFJS_WORKER = {literal(read('pdf.worker.min.mjs'))};\n")
print('wrote', out, os.path.getsize(out) // 1024, 'KB, pdfjs', version)
